{
  "$schema": "https://steeltoe.io/schema/latest/schema.json",
  "Spring": {
    "Application": {
      "Name": "ERS"
    },
    "boot": {
      "admin": {
        "client": {
          "url": "http://localhost:9090",
          "metadata": {
            "user.name": "actuatorUser",
            "user.password": "actuatorPassword"
          }
        }
      }
    }
  },
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Warning",
      "Articulate": "Information",
      "Steeltoe.Discovery":  "Information"
    }
  },
  "Management": {
    "Endpoints": {
      "Cloudfoundry": {
        "ValidateCertificates": false,
        "Exposure": {
          "Include": [
              "*"
          ]
        }
      },
      "Actuator":{
        "Exposure": {
          "Include": [
            "*"
          ]
        }
      }
    }
  },
  "Eureka": {
    "Client": {
      "Validate_certificates": false,
      "ShouldRegisterWithEureka": true
    }
  }
}
